### 카테고리 관련 API


### 서버 URL 설정 (여기에서 필요한 환경의 주석을 제거하세요)
#@SERVER_URL = http://localhost:8080
 @SERVER_URL = http://43.201.54.62:8080

### 공통 변수 설정
@email = "user@example.com"
@currentPassword = "Password123!"
@newPassword = "Password123!new"


### 유저 로그인 - 성공
POST {{SERVER_URL}}/auth/v1/users/login
Content-Type: application/json

{
  "email": {{email}},
  "password": {{currentPassword}}
}


### 가변 변수 설정 1
@jwt_token = BearereyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwZjkzNGU4OS0wMzQzLTQ0MzktYjQ4Yi05MjI4ZWRkMmRjZWQiLCJpc3MiOiJhdXRoLXNlcnZpY2UiLCJyb2xlIjoiTUFTVEVSIiwiZXhwIjoxNzI1MzMyNzM2LCJpYXQiOjE3MjUzMjkxMzZ9.VubyayzOiDEgRRwB46QqT0tVivQyQc1RHKf4Bnn2M2k
@userId = 0f934e89-0343-4439-b48b-9228edd2dced
@role = MASTER


### 카테고리 등록
POST {{SERVER_URL}}/api/v1/categories
Authorization: {{jwt_token}}
Content-Type: application/json

{
  "categoryTitle": "한식"
}

### 카테고리 목록 조회
GET {{SERVER_URL}}/api/v1/categories
Authorization: {{jwt_token}}

### 공통 변수 설정 1
@categoryId = 7abdd88c-17c8-41e9-921b-c42fc139bdd3

### 카테고리 수정
PUT {{SERVER_URL}}/api/v1/categories/{{categoryId}}
Authorization: {{jwt_token}}
Content-Type: application/json

{
  "categoryTitle": "한식2"
}

### 카테고리 삭제
DELETE {{SERVER_URL}}/api/v1/categories/{{categoryId}}
Authorization: {{jwt_token}}
