### 음식 관련 API

### 서버 URL 설정 (여기에서 필요한 환경의 주석을 제거하세요)
#@SERVER_URL = http://localhost:8080
 @SERVER_URL = http://43.201.54.62:8080

### 공통 변수 설정
@email = "user@example.com"
@currentPassword = "Password123!"
@newPassword = "Password123!new"


### 가변 변수 설정 1
@jwt_token = BearereyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwZjkzNGU4OS0wMzQzLTQ0MzktYjQ4Yi05MjI4ZWRkMmRjZWQiLCJpc3MiOiJhdXRoLXNlcnZpY2UiLCJyb2xlIjoiTUFTVEVSIiwiZXhwIjoxNzI1MzMyNzM2LCJpYXQiOjE3MjUzMjkxMzZ9.VubyayzOiDEgRRwB46QqT0tVivQyQc1RHKf4Bnn2M2k
@userId = 0f934e89-0343-4439-b48b-9228edd2dced
@role = MASTER

### 공통 변수 설정 1
@categoryId = b6ef3aa7-8b54-4d75-bd02-386716cc5b90
@restaurantId = a70ef6db-c4c2-4ba1-b898-f3401d560724

### 가게에 속한 음식 등록
POST {{SERVER_URL}}/api/v1/restaurants/{{restaurantId}}/foods
Authorization: {{jwt_token}}
Content-Type: application/json

{
  "foodInfoTitle": "테스트 음식",
  "foodInfoDesc": "이 음식은 테스트 음식입니다.",
  "foodInfoPrice": 10000
}

### 가게에 속한 음식 전체 조회 for 가게 (숨김처리 노출)
GET {{SERVER_URL}}/api/v1/restaurants/{{restaurantId}}/foods
Authorization: {{jwt_token}}

### 가게에 속한 음식 전체 조회 for 고객 (숨김처리)
GET {{SERVER_URL}}/api/v1/restaurants/{{restaurantId}}/foods
Authorization: {{jwt_token}}

### 음식 검색
GET {{SERVER_URL}}/api/v1/foods/search?keyword=테스트&page=0&size=5&sortBy=createdAt
Authorization: {{jwt_token}}

### 음식 전체 조회 FOR 운영진
GET {{SERVER_URL}}/api/v1/foods
Authorization: {{jwt_token}}

### 가변 변수 설정 1
@foodInfoId = 297660de-d9e7-4e54-a7c3-edf1df0e581b

### 음식 단건 조회 FOR 운영진
GET {{SERVER_URL}}/api/v1/foods/{{foodInfoId}}
Authorization: {{jwt_token}}

### 음식 상세 정보 수정
PUT {{SERVER_URL}}/api/v1/foods/{{foodInfoId}}
Authorization: {{jwt_token}}
Content-Type: application/json

{
  "foodInfoTitle": "업데이트된 음식",
  "foodInfoDesc": "이 음식은 업데이트된 음식입니다.",
  "foodInfoPrice": 12000
}

### 음식 숨김 처리 및 복구
PATCH {{SERVER_URL}}/api/v1/foods/{{foodInfoId}}/sale
Authorization: {{jwt_token}}


### 음식 품절 처리 및 복구
PATCH {{SERVER_URL}}/api/v1/foods/{{foodInfoId}}/sold
Authorization: {{jwt_token}}

### 음식 삭제
DELETE {{SERVER_URL}}/api/v1/foods/{{foodInfoId}}
Authorization: {{jwt_token}}