### 가게 관련 API

### 서버 URL 설정 (여기에서 필요한 환경의 주석을 제거하세요)
#@SERVER_URL = http://localhost:8080
 @SERVER_URL = http://43.201.54.62:8080

### 공통 변수 설정
@email = "user@example.com"
@currentPassword = "Password123!"
@newPassword = "Password123!new"


### 유저 로그인 - 성공
POST {{SERVER_URL}}/auth/v1/users/login
Content-Type: application/json

{
  "email": {{email}},
  "password": {{currentPassword}}
}


### 가변 변수 설정 1
@jwt_token = BearereyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwZjkzNGU4OS0wMzQzLTQ0MzktYjQ4Yi05MjI4ZWRkMmRjZWQiLCJpc3MiOiJhdXRoLXNlcnZpY2UiLCJyb2xlIjoiTUFTVEVSIiwiZXhwIjoxNzI1MzMyNzM2LCJpYXQiOjE3MjUzMjkxMzZ9.VubyayzOiDEgRRwB46QqT0tVivQyQc1RHKf4Bnn2M2k
@userId = 0f934e89-0343-4439-b48b-9228edd2dced
@role = MASTER

### 공통 변수 설정 1
@categoryId = b6ef3aa7-8b54-4d75-bd02-386716cc5b90
@restaurantId = a70ef6db-c4c2-4ba1-b898-f3401d560724



### 가게 등록
POST {{SERVER_URL}}/api/v1/restaurants
Authorization: {{jwt_token}}
Content-Type: application/json

{
  "categoryId": "{{categoryId}}",
  "restaurantName": "테스트 맛집2",
  "restaurantAddress": "서울시 종로구 세종대로 727-1",
  "restaurantPhoneNumber": "02-9999-0003",
  "restaurantIntroduce": "아임 테스트",
  "restaurantImageUrl": "http://example.com/images/good.jpg"
}


### 가게 단건 조회
GET {{SERVER_URL}}/api/v1/restaurants/{{restaurantId}}
Authorization: {{jwt_token}}

### 가게 전체 조회
GET {{SERVER_URL}}/api/v1/restaurants?page=0&size=10
Authorization: {{jwt_token}}

### 가게 정보 전체 수정
PUT {{SERVER_URL}}/api/v1/restaurants/{{restaurantId}}
Authorization: {{jwt_token}}
Content-Type: application/json

{
  "categoryId": "{{categoryId}}",
  "restaurantName": "edit 가게 이름",
  "restaurantAddress": "서울시 종로구 세종대로 717-1 3홍",
  "restaurantPhoneNumber": "02-9999-0001",
  "restaurantIntroduce": "edit 가게 이름",
  "restaurantImageUrl": "http://example.com/images/good.jpg"
}


### 가게 검색
GET {{SERVER_URL}}/api/v1/restaurants/search?keyword=edit
Authorization: {{jwt_token}}


### 가게 운영 상태 변경
PATCH {{SERVER_URL}}/api/v1/restaurants/{{restaurantId}}/status
Authorization: {{jwt_token}}
Content-Type: application/json

{
  "status": "OPEN"
}


### 가게 삭제
DELETE {{SERVER_URL}}/api/v1/restaurants/{{restaurantId}}
Authorization: Bearer {{jwt_token}}